
greetings:
    resource: "AppBundle\Controller\GreetingsController"
    type:     rest

customers:
    resource: "AppBundle\Controller\CustomersController"
    type:     rest

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
