<?php
namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CostumerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerRepository extends EntityRepository
{
}